#!/usr/bin/env bash
#
# Summary: Autopublish the packages
#
# Usage: gutdeb autopublish [dir ...]
#
#

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  for dir in "$@"; do
    if [[ ! -d "$dir" ]]; then
      continue
    fi

    if [[ ! -e "$dir/debian/watch" ]]; then
      say "::SKIP:: $dir -- there is no debian/watch file"
      continue
    fi

    autopublish "$dir"
  done
}

autopublish() {
  dir="$1"; oldpwd="$PWD"
  say "::BEGIN:: $dir"
  cd "$dir"
  version=$(app-check)
  debug "autopublish: app-check $version"
  if [[ $version == "" ]]; then
    say "it is already the latest version or there's an error"
  else
    say "found new version $version, begin to publish"
    app-publish "$version"
    #sleep 10
  fi
  cd $oldpwd
}

if [[ "$1" == "" ]]; then
  main "."
else
  main "$@"
fi
