#!/usr/bin/env bash
#
# Summary: Build the package
#
# Usage: gutdeb build
#
# Invoke debuild -b

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  package=$(get_package)
  version=$(get_version)

  # download upstream tarball and extract it.
  uscan --force-download

  tar xf "../${package}_${version}.orig.tar.gz" -C ..
  [[ -e "debian/watch-rename" ]] && debian/watch-rename $package $version
  ln -sfT  "$(pwd)/debian" "../${package}-${version}/debian"
  cd "../${package}-${version}"

  debuild -i -us -uc -b
}

main "$@"
